services:
  nexus3:
    container_name: nexus3
    image: sonatype/nexus3
    ports:
      - 8081:8081
    volumes:
      - ./data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms1g -Xmx1g
    restart: unless-stopped
