services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/vhost.d:/etc/nginx/vhost.d
      - ./certs:/etc/nginx/certs
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
