services:
  acme-companion:
    container_name: acme-companion
    image: nginxproxy/acme-companion
    volumes:
      - ./ssl:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
