services:
  chatgpt-proxy-server-arkose:
    container_name: chatgpt-proxy-server-arkose
    image: linweiyuan/chatgpt-proxy-server-arkose
    environment:
      - LOG_LEVEL=OFF
    ports:
      - 65535:65535
    restart: unless-stopped
