services:
  filerun:
    container_name: filerun
    image: filerun/filerun
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html
      - ./user-files:/user-files
    environment:
      - FR_DB_HOST=mysql
      - FR_DB_PORT=3306
      - FR_DB_NAME=filerun
      - FR_DB_USER=filerun
      - FR_DB_PASS=filerun
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_USER_ID=33
      - APACHE_RUN_GROUP=www-data
      - APACHE_RUN_GROUP_ID=33
    networks:
      - mysql
    restart: unless-stopped

networks:
  mysql:
    external: true
