services:
  redis-master:
    container_name: redis-master
    image: redis:7-alpine
    ports:
      - 6380:6379
    volumes:
      - ./redis-master/conf:/conf
      - ./redis-master/data:/data
    environment:
      - TZ=Asia/Shanghai
    networks:
      - redis
    command: redis-server /conf/redis.conf
    restart: unless-stopped

  redis-slave-1:
    container_name: redis-slave-1
    image: redis:7-alpine
    ports:
      - 6381:6379
    volumes:
      - ./redis-slave-1/conf:/conf
      - ./redis-slave-1/data:/data
    environment:
      - TZ=Asia/Shanghai
    networks:
      - redis
    command: redis-server /conf/redis.conf
    restart: unless-stopped

  redis-slave-2:
    container_name: redis-slave-2
    image: redis:7-alpine
    ports:
      - 6382:6379
    volumes:
      - ./redis-slave-2/conf:/conf
      - ./redis-slave-2/data:/data
    environment:
      - TZ=Asia/Shanghai
    networks:
      - redis
    command: redis-server /conf/redis.conf
    restart: unless-stopped

networks:
  redis:
    name: redis
