services:
  nacos-server-1:
    container_name: nacos-server-1
    image: nacos/nacos-server
    ports:
      - 8849:8848
      - 9849:9848
    volumes:
      - ./nacos-server-1/logs:/home/nacos/logs
    environment:
      - PREFER_HOST_MODE=hostname
      - NACOS_SERVERS=nacos-server-1:8848 nacos-server-2:8848 nacos-server-3:8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
    networks:
      - mysql
    restart: unless-stopped

  nacos-server-2:
    container_name: nacos-server-2
    image: nacos/nacos-server
    ports:
      - 8850:8848
      - 9850:9848
    volumes:
      - ./nacos-server-2/logs:/home/nacos/logs
    environment:
      - PREFER_HOST_MODE=hostname
      - NACOS_SERVERS=nacos-server-1:8848 nacos-server-2:8848 nacos-server-3:8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
    networks:
      - mysql
    restart: unless-stopped

  nacos-server-3:
    container_name: nacos-server-3
    image: nacos/nacos-server
    ports:
      - 8851:8848
      - 9851:9848
    volumes:
      - ./nacos-server-3/logs:/home/nacos/logs
    environment:
      - PREFER_HOST_MODE=hostname
      - NACOS_SERVERS=nacos-server-1:8848 nacos-server-2:8848 nacos-server-3:8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
    networks:
      - mysql
    restart: unless-stopped

networks:
  mysql:
    external: true
