services:
  redis-sentinel-1:
    container_name: redis-sentinel-1
    image: redis:7-alpine
    ports:
      - 26380:26379
    volumes:
      - ./redis-sentinel-1/conf/sentinel.conf:/conf/sentinel.conf
      - ./redis-sentinel-1/data:/data
    environment:
      - TZ=Asia/Shanghai
    networks:
      - redis
    command: redis-sentinel /conf/sentinel.conf
    restart: unless-stopped

  redis-sentinel-2:
    container_name: redis-sentinel-2
    image: redis:7-alpine
    ports:
      - 26381:26379
    volumes:
      - ./redis-sentinel-2/conf/sentinel.conf:/conf/sentinel.conf
      - ./redis-sentinel-2/data:/data
    environment:
      - TZ=Asia/Shanghai
    networks:
      - redis
    command: redis-sentinel /conf/sentinel.conf
    restart: unless-stopped

  redis-sentinel-3:
    container_name: redis-sentinel-3
    image: redis:7-alpine
    ports:
      - 26382:26379
    volumes:
      - ./redis-sentinel-3/conf/sentinel.conf:/conf/sentinel.conf
      - ./redis-sentinel-3/data:/data
    environment:
      - TZ=Asia/Shanghai
    networks:
      - redis
    command: redis-sentinel /conf/sentinel.conf
    restart: unless-stopped

networks:
  redis:
    external: true
