services:
  acme:
    container_name: acme
    image: neilpang/acme.sh
    command: daemon
    volumes:
      - ./ssl:/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
